import type { Config } from 'tailwindcss'

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1c1c19",
        "on-surface-variant": "#434844",
        "on-background": "#1c1c19",
        "on-primary": "#ffffff",
        "on-primary-container": "#f6fff6",
        "on-primary-fixed": "#0e1f16",
        "on-primary-fixed-variant": "#394b40",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#77331c",
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-fixed-variant": "#76321c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#211a17",
        "on-tertiary-fixed-variant": "#4e4541",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#F9F6F1",
        "surface-bright": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "surface-variant": "#e5e2dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ee",
        "surface-container": "#f0ede9",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "surface-tint": "#506357",
        "background": "#F9F6F1",
        "primary": "#4e6054",
        "primary-container": "#66796c",
        "primary-fixed": "#d3e8d8",
        "primary-fixed-dim": "#b7cbbd",
        "secondary": "#944931",
        "secondary-container": "#fd9d7f",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59e",
        "tertiary": "#645a55",
        "tertiary-container": "#7d726e",
        "tertiary-fixed": "#eee0da",
        "tertiary-fixed-dim": "#d1c4be",
        "outline": "#737873",
        "outline-variant": "#c3c8c2",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        "inverse-primary": "#b7cbbd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "Newsreader", "serif"],
        body: ["var(--font-headline)", "Newsreader", "serif"],
        label: ["var(--font-label)", "Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
export default config
